name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: 
          |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Check out Luos repository
      uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Create env repo
      run: 
           |
        cd ..
        git clone https://github.com/Luos-io/LuosHAL.git
        git clone https://github.com/Luos-io/Examples.git
        export PLATFORMIO_LIB_EXTRA_DIRS=/home/runner/work/Luos
    - name: Run PlatformIO
      run:
           |
        cd ..
        cd Examples
        git checkout pre_release
        platformio run -d Projects/Button/
        

        
    
