name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Check out Luos repository
      uses: actions/checkout@v2
    - name: Create env repo
      run: |
        cd ..
        ls
        git clone https://github.com/Luos-io/LuosHAL.git
        git clone https://github.com/Luos-io/Examples.git
        ls
        export PLATFORMIO_LIB_EXTRA_DIRS=pwd
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run:
           |
        ls
        

        
    
