name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Check out Luos repository
      uses: actions/checkout@v2
      with:
            Luos-io/LuosHAL
            Luos-io/Examples
    - name: Create env repo
      run: |
            pwd
            ls
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        export PLATFORMIO_LIB_EXTRA_DIRS=pwd/LuosLib
    - name: Run PlatformIO
      run:
           |
        pwd
        ls
        

        
    
